export interface Message {
    ack?: number,
    body: string,
    deviceType?: string,
    forwardingScore?: number,
    from: string,
    fromMe: boolean,
    hasMedia?: boolean,
    hasQuoteMsg?: boolean,
    hasReaction?: boolean,
    id?: {
        fromMe: boolean,
        id: string,
        remote: string,
        _serialized: string,
    },
    isForwarded?: boolean,
    ifGif?: boolean,
    isStarred?: boolean,
    isStatus?: boolean,
    links: string[],
    mentionedIds: string[],
    timestamp: number,
    to: string,
    type: string,
    vCards: string[],
    _data: any,
    author: string,
}